### ISSUE TITLE
TSWANA

### ISSUE THREAD

**Issue by javabmessage** [skifree-snowmonster/taskhive#21]
Do we really need TSWANA at this point? Seems a bit overkill.

**Comment by skifree-snowmonster** [comment]
Taskhive will be useful to many people in many countries that are already developed, perhaps even as a means of primary income for some, or just secondary. For lower income countries however, it could be a way to save someones life. It could easily be a means for primary income and make some real changes. For that reason alone, I would prefer that translations not ignore countries that might be considered to "need it the most". 

To answer your question with a question: Where is TSWANA spoken? Are they primarily poor countries? Do they have access to a computer/mobile phone despite being poor (if poor)? These are more important than "how many people speak it" to me.
